### ISSUE TITLE
Create Two Distinct Logins for Users & Admins

### ISSUE THREAD

**Issue by TheAndyStumpf** [acesinc/bullpen-center#39]
Create two distinct logins: one for general users, one for admins.  Admins would have the current access they have in Bullpen now - ability to add/subtract apps, make changes to wording, upload new icons, etc., and should be limited to the Bullpen team only (Andy, Manny, Dylan, & Myles).  General users (basically everyone else) would be able to use the tool, but not make changes to it.  Leave current 'bigbrother' login & password the same for general users, and create a new login & password for the admins.

**Comment by dylankolson** [comment]
This has been completed. See @dylankolson for the admin account info.
